# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bruh.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbruh.proto\"Q\n\tapp_entry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x03 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x04 \x01(\t\".\n\rapp_entry_res\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"V\n\x08req_vote\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x12\n\nlastLogInd\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"0\n\x0creq_vote_res\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x12\n\nvote_grant\x18\x02 \x01(\x08\"\x1e\n\x0f\x63lient_findLead\x12\x0b\n\x03not\x18\x01 \x01(\x05\"-\n\x0cres_findLead\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04node\x18\x02 \x01(\x05\"&\n\nclient_set\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"\x1a\n\x07res_set\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nclient_get\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\x07res_get\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xd0\x01\n\x04Node\x12*\n\x0crequest_vote\x12\t.req_vote\x1a\r.req_vote_res\"\x00\x12,\n\x0c\x61ppend_entry\x12\n.app_entry\x1a\x0e.app_entry_res\"\x00\x12-\n\x08\x66indLead\x12\x10.client_findLead\x1a\r.res_findLead\"\x00\x12\x1f\n\x04sett\x12\x0b.client_set\x1a\x08.res_set\"\x00\x12\x1e\n\x03get\x12\x0b.client_get\x1a\x08.res_get\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bruh_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APP_ENTRY']._serialized_start=14
  _globals['_APP_ENTRY']._serialized_end=95
  _globals['_APP_ENTRY_RES']._serialized_start=97
  _globals['_APP_ENTRY_RES']._serialized_end=143
  _globals['_REQ_VOTE']._serialized_start=145
  _globals['_REQ_VOTE']._serialized_end=231
  _globals['_REQ_VOTE_RES']._serialized_start=233
  _globals['_REQ_VOTE_RES']._serialized_end=281
  _globals['_CLIENT_FINDLEAD']._serialized_start=283
  _globals['_CLIENT_FINDLEAD']._serialized_end=313
  _globals['_RES_FINDLEAD']._serialized_start=315
  _globals['_RES_FINDLEAD']._serialized_end=360
  _globals['_CLIENT_SET']._serialized_start=362
  _globals['_CLIENT_SET']._serialized_end=400
  _globals['_RES_SET']._serialized_start=402
  _globals['_RES_SET']._serialized_end=428
  _globals['_CLIENT_GET']._serialized_start=430
  _globals['_CLIENT_GET']._serialized_end=455
  _globals['_RES_GET']._serialized_start=457
  _globals['_RES_GET']._serialized_end=498
  _globals['_NODE']._serialized_start=501
  _globals['_NODE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
